### ISSUE TITLE
dcm2nii

### ISSUE THREAD

**Issue by yinkaiming1987** [muschellij2/dcm2niir#1]
Dear John,

The package works. Could I ask does the "dcm2nii()" represent the dcm2niix software? What about if I want to use the dcm2nii software then, which command should I call? How to use the flags then in this R package? e.g. -input, -output, -x, etc, are them available?

Thanks a lot,
Kaiming

**Comment by neuroconductor** [comment]
Please read the documentation of a package before posting issues.

``` r
library(dcm2niir)
?dcm2nii
```

Look at the `dcm2niicmd` argument

**Comment by yinkaiming1987** [comment]
Thanks John,

The last question, now I use command as:

dcm2nii("~/Desktop", dcm2niicmd="dcm2nii")

It works well, but dcm2nii  originally has a lot of options, e.g. -x, so how to pass this "-x" option to dcm2nii() function?

Best,
Kaiming

**Comment by muschellij2** [comment]
It is currently not implemented.   You are welcome to add to this package with a [pull request](https://yangsu.github.io/pull-request-tutorial/)

**Comment by neurolabusc** [comment]
John-
  I added the crop function to the 5May2016 version of dcm2niix, so I think you can close this issue.
